"""Subclass of ShootSubs, which is generated by wxFormBuilder."""

import wx
import movies_subs_gui

# Implementing ShootSubs
class movies_subsShootSubs( movies_subs_gui.ShootSubs ):
	def __init__( self, parent ):
		movies_subs_gui.ShootSubs.__init__( self, parent )
	
	# Handlers for ShootSubs events.
	def do_init_config( self, event ):
		# TODO: Implement do_init_config
		pass
	
	def do_ok_click( self, event ):
		# TODO: Implement do_ok_click
		pass
	
	
